# *  Module Name: unit-tests.yml
# *  Purpose: GitHub Workflow object that runs unit tests on the project when a PR is made to the develop branch.
# *  Inputs: None
# *  Outputs: None
# *  Additional code sources: None
# *  Developers: Jacob Wilkus
# *  Date: 2/25/2025
# *  Last Modified: 2/25/2025
# *  Preconditions: None
# *  Postconditions: None
# *  Error/Exception conditions: None
# *  Side effects: None
# *  Invariants: None
# *  Known Faults: None encountered

name: Unit Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest taskw-ng
          sudo apt-get install taskwarrior
      - name: Initialize Taskwarrior
        run: |
          echo "data.location=~/.task" > ~/.taskrc
      - name: API Tests
        run: |
          pytest api-tests.py
  data-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest taskw-ng
          sudo apt-get install taskwarrior
      - name: Initialize Taskwarrior
        run: |
          echo "data.location=~/.task" > ~/.taskrc
      - name: Data Tests
        run: |
          pytest data-tests.py
  gui-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest taskw-ng pyside6 qtpy
          sudo apt-get install taskwarrior libgl1
      - name: Initialize Taskwarrior
        run: |
          echo "data.location=~/.task" > ~/.taskrc
      - name: GUI Tests
        run: |
          python -m venv env
          source env/bin/activate
          export QT_GRAPHICS_RENDERER=raster
          pytest gui-tests.py